-- Create the BATCH_STEP_EXECUTION_SEQ table for generating step execution IDs
CREATE TABLE BATCH_STEP_EXECUTION_SEQ (
    ID BIGINT NOT NULL,
    UNIQUE_KEY CHAR(1) NOT NULL,
    CONSTRAINT STEP_EXECUTION_SEQ_PK PRIMARY KEY (ID, UNIQUE_KEY)
);
