-- Create the BATCH_JOB_EXECUTION_SEQ table for generating job execution IDs
CREATE TABLE BATCH_JOB_EXECUTION_SEQ (
    ID BIGINT NOT NULL,
    UNIQUE_KEY CHAR(1) NOT NULL,
    CONSTRAINT JOB_EXECUTION_SEQ_PK PRIMARY KEY (ID, UNIQUE_KEY)
);