-- Create the BATCH_JOB_SEQ table for generating job instance IDs
CREATE TABLE IF NOT EXISTS BATCH_JOB_SEQ (
    ID BIGINT NOT NULL,
    UNIQUE_KEY CHAR(1) NOT NULL,
    CONSTRAINT JOB_SEQ_PK PRIMARY KEY (ID, UNIQUE_KEY)
);